### PR TITLE
Fix for new youtube version

### PR DESCRIPTION
**Pull request by ChristophPech**

### CODE REVIEW

**Comment by SandPox** [comment]
Wow nice, could you release an APK meanwhile?

**Comment by wanam** [comment]
I just released an update, but not based on Christoph patch, i still need more time to test some of his refactoring changes.

**Comment by ChristophPech** [comment]
One main change is that I am going over all obfuscated classes in the package instead of trying all three letter combinations because they also use four letter classes. The obfuscator might use these one day. Then I am changing the value of the timestamp in beforehook instead of after so I don't need to touch the member variable.
While testing it I found out some if the long values are timestamps in milliseconds but some seem to be durations or at least relative values so I set them to zero, but a large value number works as well.

**Comment by SandPox** [comment]
I'm still randomly seeing ads when video started, also YouTube has crashed once when the video is playing.

There's nothing interesting in the xposed log so I didn't bother...

-------- Original Message --------

**Comment by Aviv258958** [comment]
I have tried this one and the last update wanam provided.
This one works just fine, haven't had much testing tho , loaded 10 videos+ and haven't got any ad yet besides the main screen where you have an ad video but I don't really mind that

Wanam's version doesn't work for me (using Pixel 2 XL, Android 8.1)
Thanks for the contribution :)

**Comment by widmfeli** [comment]
please post compiled version so we can help with testing

**Comment by street-grease-coder** [comment]
> i've compiled the PR from @ChristophPech and it's working really good, thanks! There's not even ads in the video, I'll leave the apk file here:
> https://drive.google.com/open?id=1PRreR2cBpdt08T0-aTx_1us_CSb5OQxd

thanks for compile, package installer tells me APK file is corrupt Android 7.1.2

**Comment by SandPox** [comment]
I installed it successfully, make sure you removed the old one first because signature won't match

**Comment by street-grease-coder** [comment]
mea culpa, indeed the solution was this simple. I do still see videos at the beginning, but I imagine this might be due to cache files

**Comment by SandPox** [comment]
@ChristophPech ads has appeared again in version 13.37.52, could you please check?

**Comment by ChristophPech** [comment]
@SandPox it should work now again

**Comment by SandPox** [comment]
yes, it's working now, if anyone want the prebuilt apk: https://drive.google.com/open?id=1kDBQq7FMIUThD-C1jWI2kjkF8hMYW7rl

uninstall the previous version first if install failed

**Comment by ngosang** [comment]
@wanam the official release is not working since 2 months. I'm using this patch, but this should be mainstream so all of us could update with xposed updater.

**Comment by AuroraWright** [comment]
Can confirm on Android 7.1 and latest Xposed, official 4.3.3 doesn't hide ads at the beginning of videos with YT 13.39.51. This PR fixed the issue

**Comment by SandPox** [comment]
@monkey000 could you try clear data of youtube app? I'm using 6.0 and latest youtube version, there's no ads or crash here

**Comment by monkey000** [comment]
@SandPox Tried to clear the data and still crash.
Now I am using the YouTube Vanced module in the Magisk framework, and no ads will appear. Otherwise I will consider whether to open YouTube Premium.

**Comment by ChristophPech** [comment]
The SandPox binary is from before my fix for 8.1

**Comment by SandPox** [comment]
Where's your fix for 8.1? Pretty sure I was complied your latest commit on your repo eeafb5a which is 12 days ago

**Comment by ChristophPech** [comment]
Sorry, I didn't see you already updated it.

**Comment by monkey000** [comment]
@SandPox I am very sorry, it's my fault.I did not see the link you updated later. I downloaded and installed the first apk.

**Comment by SandPox** [comment]
@ChristophPech the ads has come back, could you update it?

**Comment by AuroraWright** [comment]
Which YouTube version? I don't see them on 13.41.53

**Comment by rishav394** [comment]
I see adds too now on the latest version. Only in the starting though. Not in between the video.

**Comment by SandPox** [comment]
I'm starting to see some ads between video now

**Comment by AuroraWright** [comment]
Still nothing here on latest YouTube, are you sure you emptied the YouTube app's data after you installed this fork?

**Comment by rishav394** [comment]
Idk can't say anything for sure. Ads have stopped again. Huh. 🤔🤔
Also merge this PR pls ofc after resolving the conflicts.

**Comment by ngosang** [comment]
Not working in last version :(

**Comment by street-grease-coder** [comment]
It's stable for me, but some ads keep showing again

**Comment by acsway878787** [comment]
It doesn't work on the latest version, any way to fix it? The ads are disturbing.

**Comment by ngosang** [comment]
@ChristophPech Seems like the original author lost interest... Could you take care of this project or make a fork?

**Comment by ChristophPech** [comment]
@ngosang I don't have the time to continue this either.

**Comment by acsway878787** [comment]
@ChristophPech 
Maybe you can give me some hint of maintaining this module then I can continue this project.
It's really hard to figure out what to do with this only by viewing the codes...

**Comment by wanam** [comment]
@acsway878787 unfortunately this is how it was done all the time, you need to pinpoint some classes, and try to analyze them based on the json keys strings and logging messages.

**Comment by minhng99** [comment]
Try Youtube Vance, it's pretty good

**Comment by ohyeah521** [comment]
try this:
https://github.com/ohyeah521/NoAds-For-YouTube/releases

**Comment by ohyeah521** [comment]
> @ngosang I don't have the time to continue this either.

I just lost my job and I have time to do this. try this:
https://github.com/ohyeah521/NoAds-For-YouTube/releases

i had test on my phone, If there is a problem, please submit a bug

**Comment by ngosang** [comment]
Sorry, I'm using Youtube Vance now.

**Pull request closed without merging**
